#!/usr/bin/env bash

gh=timm

help() { 
  tput bold; tput setaf 3
  cat<<EOF

zen [OPTION]

options:
-S     git status all
-h     help
-I     install (do this first)
-V     install vim (do this first, if you like vim)
-s     git save all (git push)
-u     update all (configs reset, git pull all)
EOF
echo ""
tput bold; tput setaf 241
grep '^alias' $Zen/master
tput sgr0
}

Zen=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
ZenTmp=$HOME/tmp/zen

mkdir -p $ZenTmp
mkdir -p docs
chmod +x $Zen/master

alias ls="ls -G"
alias gp="git add *; git commit -am saving ; git push -q; git status"
alias vi='vim -u $ZenTmp/dotvimrc'
alias tmux='tmux -f $ZenTmp/dottmux'
alias zen="./zen "

docs() { 
   f=${1%.*}
   (pdoc3 --config sort_identifiers=False -o docs  --force --html $f.py > /dev/null
   mv docs/$f.html docs/index.html)
}
color() { tput bold; tput setaf 3; echo "$*"; tput sgr0; }

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "🌏 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

want=$ZenTmp/dotvimrc;        [ -f "$want" ] || (cat $Zen/dotvimrc > $want)
want=$ZenTmp/dottmux;         [ -f "$want" ] || (cat $Zen/dottmux > $want)
want=$HOME/.gitignore_global; [ -f "$want" ] || (cat $Zen/dotgitignore > $want)
want=docs/.nojeykll;          [ -f "$want" ] || touch $want

git add docs/.nojeykll
git config --global core.excludesfile $HOME/.gitignore_global
git config --global pull.rebase false

for p in pdoc3 ; do
  (pip3 list | grep $p > /dev/null) || sudo pip3 install $p
done


hello() { tput bold; tput setaf 3; cat<<'EOF'
 ________                      
/\_____  \                     
\/____//'/'      __     ___    
     //'/'     /'__`\ /' _ `\  
    //'/'___  /\  __/ /\ \/\ \ 
    /\_______\\ \____\\ \_\ \_\
    \/_______/ \/____/ \/_/\/_/
EOF
   tput sgr0
}
Zens=$PYTHONPATH
for d in $Zen/../*; do
  if [ -d "$d" ] && [[ ":$Zens:" != *":$d:"* ]]; then Zens="$d:$Zens"; fi; done

alias python="PYTHONPATH=\"$Zens\" python3 "

o() {   printf "\n#-------\n%% "
        echo "$@"
        $@; }
  
master() {
  com=$1; shift
  [[ "$com" == "-h" ]] &&  help
  if [[ "$com" == "-I" ]]; then
    for d in $*; do
      if [[ ! -d "../$d" ]]; then
        color installing $d
        echo git clone http://github.com/$gh/$d ../$d
        git clone http://github.com/$gh/$d ../$d
      fi; done
  elif [[ "$com" == "-u" ]]; then
  	for d in $Zen/../*; do
      if [ -d "$d" ]; then
        (cd $d; color updating $d; git pull -q
        [[ -f .gitignore ]] || cat $Zen/dotgitignore > .gitignore
        git add .gitignore
        )
      fi
    done
    rm -rf $ZenTmp/*
    rm -f $HOME/.gitignore_global
    . $Zen/master
  elif [[ "$com" == "-S" ]]; then
  	for d in $Zen/../*; do
      echo $d
      if [ -d "$d" ]; then
    	  (cd $d; color stats $d;
         git status); 
       fi
    done
  elif [[ "$com" == "-d" ]]; then
     docs $1
  elif [[ "$com" == "-s" ]]; then
  	for d in $Zen/../*; do
      if [ -d "$d" ]; then
        (cd $d; color saving $d; 
         git add * ; git commit -am saving; git push -q); 
      fi
    done
  elif [[ "$com" == "-V" ]]; then
     if [ ! -d "$HOME/.vim/bundle" ]; then
        git clone https://github.com/VundleVim/Vundle.vim.git \
           ~/.vim/bundle/Vundle.vim
     fi
     for d in $HOME/.vim/bundle/*; do
       (cd $d; color updating vim $d; 
        git pull -q)
    done
    vim -u $ZenTmp/dotvimrc  +PluginInstall +qall
 fi
 } 

