#!/usr/bin/env bash

help() { 
  tput bold; tput setaf 6
  cat<<EOF

zen [OPTION]

options:
-S     git status all
-h     help
-I     install (do this first)
-V     install vim (do this first, if you like vim)
-s     git save all (git push)
-u     update all (configs reset, git pull all)
EOF
echo ""
tput bold; tput setaf 241
grep '^alias' $Zen/zen
tput sgr0
}

Zen=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
ZenTmp=$HOME/tmp/zen

mkdir -p $ZenTmp
chmod +x $Zen/zen

alias ls="ls -G"
alias gp="git add *; git commit -am saving; git push; git status"
alias vi='vim -u $ZenTmp/dotvimrc'
alias tmux='tmux -f $ZenTmp/dottmux'

docs() { 
   (pdoc3 --config sort_identifiers=False -o .  --force --html $1.py
   mv $1.html index.html)
}
red() { tput bold; tput setaf 1; echo "$*"; tput sgr0; }

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "🌊 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

want=.gitignore;       [ -f "$want" ] || (cat $Zen/dotgitignore > $want)
want=$ZenTmp/dotvimrc; [ -f "$want" ] || (cat $Zen/dotvimrc > $want)
want=$ZenTmp/dottmux;  [ -f "$want" ] || (cat $Zen/dottmux > $want)

for p in pdoc3 fred; do
  (pip3 list | grep $p > /dev/null) || sudo pip3 install $p
done

git config --global pull.rebase false

hello() { tput bold; tput setaf 3; cat<<'EOF'
 ________                      
/\_____  \                     
\/____//'/'      __     ___    
     //'/'     /'__`\ /' _ `\  
    //'/'___  /\  __/ /\ \/\ \ 
    /\_______\\ \____\\ \_\ \_\
    \/_______/ \/____/ \/_/\/_/
EOF
   tput sgr0
}
master() {
  com=$1; shift
  [[ "$com" == "-h" ]] &&  help
  if [[ "$com" == "-I" ]]; then
    red installing zen
    for d in $*; do
      if [[ ! -d "../$d" ]]; then
        red installing $d
        git clone http://$web/$d ../$d
      fi; done
  elif [[ "$com" == "-u" ]]; then
  	for d in $Zen/../*; do
      if [ -d "$d" ]; then
        (cd $d; red updating $d; git pull
        [[ -f .gitignore ]] || cat $Zen/dotgitignore > .gitignore
        git add .gitignore
        )
      fi
    done
    rm -rf $ZenTmp/*
    . $Zen/zen
  elif [[ "$com" == "-S" ]]; then
  	for d in $Zen/../*; do
      echo $d
      if [ -d "$d" ]; then
    	  (cd $d; red stats $d;
         git status); 
       fi
    done
  elif [[ "$com" == "-s" ]]; then
  	for d in $Zen/../*; do
      if [ -d "$d" ]; then
        (cd $d; red saving $d; 
         git add *; git commit -am saving; git push); 
      fi
    done
  elif [[ "$com" == "-V" ]]; then
     if [ ! -d "$HOME/.vim/bundle" ]; then
        git clone https://github.com/VundleVim/Vundle.vim.git \
           ~/.vim/bundle/Vundle.vim
     fi
     for d in $HOME/.vim/bundle/*; do
       (cd $d; red updating vim $d; 
        git pull)
    done
    vim -u $ZenTmp/dotvimrc  +PluginInstall +qall
 fi
 } 

