#!/usr/bin/env bash

help() { cat<<EOF
-S     git status all
-h     help
-I     install (do this first)
-V     install vim (do this first, if you like vim)
-s     git save all (git push)
-u     update all (configs reset, git pull all)
EOF
}

Zen=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
ZenTmp=$HOME/tmp/zen

mkdir -p $ZenTmp
chmod +x $Zen/zen

alias ls="ls -G"
alias gp="git add *; git commit -am saving; git push; git status"
alias vi='vim -u $ZenTmp/dotvimrc'
alias tmux='tmux -f $ZenTmp/dottmux'

docs() { 
   (pdoc3 --config sort_identifiers=False -o .  --force --html $1.py
   mv $1.html index.html)
}
red() { tput bold; tput setaf 1; echo "$*"; tput sgr0; }

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "🌊 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

want=$ZenTmp/dotvimrc; [ -f "$want" ] || (cat $Zen/dotvimrc > $want)
want=$ZenTmp/dottmux;  [ -f "$want" ] || (cat $Zen/dottmux > $want)
sudo pip3 install pdoc3

zen() {
  com=$1; shift
  [[ "$com" == "-h" ]] &&  help
  if [[ "$com" == "-I" ]]; then
    for d in $*; do
      if [[ ! -d "../$d" ]]; then
        red installing $d
        git clone http://$web/$d ../$d
        if ../$d/$d.py; then 
          chmod +x ../$d/$d.py; fi
      fi; done
  elif [[ "$com" == "-u" ]]; then
  	for d in $*; do
      (cd ../$d; red updating $d; git pull
      [[ -f .gitignore ]] || cat $Zen/gitignore > .gitignore
      git add .gitignire
      )
    done
    rm -rf $ZenTmp/*
    . $Zen/zen
  elif [[ "$1" == "-S" ]]; then
  	for d in $*; do
  	  (cd ../$d; red stats $d;
       git status); done
  elif [[ "$com" == "-s" ]]; then
  	for d in $*; do
      (cd ../$d; red saving $d; 
       git add *; git commit -am saving; git push); done
  elif [[ "$com" == "-V" ]]; then
     if [ ! -d "$HOME/.vim/bundle" ]; then
        git clone https://github.com/VundleVim/Vundle.vim.git \
           ~/.vim/bundle/Vundle.vim
     fi
     for d in $HOME/.vim/bundle/*; do
       (cd $d; red updating vim $d; 
        git pull)
    done
    vim -u $ZenTmp/dotvimrc  +PluginInstall +qall
 fi
 } 

